# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

remote_theme           : "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin    : "dirt" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "CC Lab @ xjtlu"  # UPDATE THIS
title_separator          : "-"
name                     : "CC Lab"  # UPDATE THIS
description              : "Research laboratory focused on structural bioinformatics"  # UPDATE THIS
url                      : "https://skblnw.github.io"  # UPDATE THIS with your GitHub Pages URL
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "skblnw/skblnw.github.io"  # GitHub username/repo-name
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
words_per_minute         : 200
search                   : true
search_full_content      : false
search_provider          : # lunr (default), algolia, google

# Social Sharing
twitter:
  username               : # UPDATE THIS with your lab twitter handle
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
social:
  type                   : Organization # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    # - "https://twitter.com/yourlab"
    # - "https://github.com/yourlab"

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : false

# Site Author
author:
  name             : "Kevin"  # UPDATE THIS
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Principal Investigator at XJTLU"  # UPDATE THIS
  location         : "Suzhou/Shanghai/Hong Kong/Columbus OH"  # UPDATE THIS
  email            : "Chun.Chan@xjtlu.edu.cn"  # UPDATE THIS
  github           : # Username without @ sign
  twitter          : # Username without @ sign

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
  - /utils # utility scripts
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
timezone: America/Los_Angeles # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Collections
collections_dir: collections
collections:
  people:
    output: true
    permalink: /:collection/:name
  posts:
    output: true
    permalink: /:categories/:name

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: false
      read_time: false
      comments: false
      share: true
      related: false
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: true
  # _people
  - scope:
      path: ""
      type: people
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false