name: Validate Student PR

on:
  pull_request:
    paths:
      - 'STUDENT_ZONE/**'
      - 'collections/_posts/**'
      - 'assets/images/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install pyyaml pillow
        
    - name: Run validation script
      run: |
        python utils/validate_student_pr.py
        
    - name: Check YAML syntax
      run: |
        find STUDENT_ZONE -name "*.yml" -o -name "*.yaml" | xargs -I {} python -c "import yaml; yaml.safe_load(open('{}'))"
        
    - name: Check Markdown syntax
      run: |
        find STUDENT_ZONE -name "*.md" | head -20  # Limit to prevent timeout
        
    - name: Validate image sizes
      run: |
        find STUDENT_ZONE -name "*.jpg" -o -name "*.png" | while read file; do
          size=$(stat -f%z "$file" 2>/dev/null || stat -c%s "$file" 2>/dev/null)
          if [ "$size" -gt 2097152 ]; then  # 2MB limit
            echo "Error: $file is larger than 2MB ($size bytes)"
            exit 1
          fi
        done
        
    - name: Check for forbidden edits
      run: |
        if git diff --name-only origin/main HEAD | grep -E "^(PI_ONLY/|_config\.yml|_data/navigation\.yml)"; then
          echo "Error: Changes detected in protected areas"
          exit 1
        fi

  label-pr:
    runs-on: ubuntu-latest
    needs: validate
    if: success()
    
    steps:
    - name: Label PR as student contribution
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['student-contribution', 'ready-for-review']
          })